name: main (Go)

on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'

jobs:
  lint-go:
    name: Lint (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-check
        env:
          GOOS: js
          GOARCH: wasm
